### ISSUE TITLE
get this error a lot when writing code in a class

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#115]
The problems panels shows some errors for a moment, then they disappear - this error is flashed on screen and present in the language server logs

```
node:14923) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classStatements' of undefined
    at BsClassValidator.findClasses (/home/george/hope/open-source/vsc/brighterscript/src/validators/ClassValidator.ts:262:39)
    at BsClassValidator.validate (/home/george/hope/open-source/vsc/brighterscript/src/validators/ClassValidator.ts:22:14)
    at Scope.validateClasses (/home/george/hope/open-source/vsc/brighterscript/src/Scope.ts:462:19)
    at Scope.validate (/home/george/hope/open-source/vsc/brighterscript/src/Scope.ts:362:14)
    at Program.validate (/home/george/hope/open-source/vsc/brighterscript/src/Program.ts:447:19)
    at /home/george/hope/open-source/vsc/brighterscript/src/LanguageServer.ts:577:46
    at Array.map (<anonymous>)
    at LanguageServer.reloadWorkspaces (/home/george/hope/open-source/vsc/brighterscript/src/LanguageServer.ts:574:29)
    at async LanguageServer.onDidChangeWatchedFiles (/home/george/hope/open-source/vsc/brighterscript/src/LanguageServer.ts:687:13)
warning.js:27
```

**Comment by elsassph** [comment]
Ha, having this error as well at times in regular `.brs` files.

**Comment by georgejecook** [comment]
not seen this in a long time.
