### ISSUE TITLE
bsc crashes when rootDir is an absolute unix path

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#136]
when using a config with rootDir `/tmp/buildTmp/src` bsc crashes with the following:

```config: development, using configFiles [ 'manifest',
  'source/**/*.*',
  'components/**/*.*',
  'images/**/*.*',
  'font/**/*.*',
  { src: '../src-dev/**/*', dest: '' } ]
using config { stagingFolderPath: 'build',
  createPackage: false,
  rootDir: '/tmp/buildTmp/src',
  autoImportComponentScript: true,
  files: 
   [ 'manifest',
     'source/**/*.*',
     'components/**/*.*',
     'images/**/*.*',
     'font/**/*.*',
     { src: '../src-dev/**/*', dest: '' } ],
  diagnosticFilters: [ { codes: [Array] } ],
  ignoreErrorCodes: [ 1004, 1013, 1107 ] }
[11:40:59] 'compile' errored after 1.96 ms
[11:40:59] SyntaxError: Unexpected token / in JSON at position 664
    at JSON.parse (<anonymous>)
    at RokuDeploy.getOptions (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/roku-deploy/src/RokuDeploy.ts:711:36)
    at Util.normalizeConfig (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/brighterscript/src/util.ts:258:51)
    at Util.normalizeAndResolveConfig (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/brighterscript/src/util.ts:230:27)
    at ProgramBuilder.run (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/node_modules/brighterscript/src/ProgramBuilder.ts:69:39)
    at /home/george/hope/smc/pot-smithsonian-channel-roku-xm/gulpfile.ts:241:17
    at step (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/gulpfile.ts:33:23)
    at Object.next (/home/george/hope/smc/pot-smithsonian-channel-roku-xm/gulpfile.ts:14:53)
    at /home/george/hope/smc/pot-smithsonian-channel-roku-xm/gulpfile.ts:8:71
    at new Promise (<anonymous>)
[11:40:59] 'build' errored after 261 ms
```

if I change dir, then run bsc with rootdir `src` it is fine.

please note single quotes in config are from `inspect` output; the json passed into bsc is valid. @TwitchBronBron you can see this in S gulpfile.ts

**Comment by TwitchBronBron** [comment]
Closing because I believe this was related to [roku-deploy#38](https://github.com/rokucommunity/roku-deploy/issues/38) which was resolved in brighterscript@0.11.1
