### ISSUE TITLE
error in onSignatureHelp: Cannot read property 'kind' of undefinedTypeError

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#357]
```
[Error - 2:14:06 PM] error in onSignatureHelp: Cannot read property 'kind' of undefinedTypeError: Cannot read property 'kind' of undefined
    at BrsFile.getClassFromMReference (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.6/node_modules/brighterscript/dist/files/BrsFile.js:775:27)
    at Program.getSignatureHelp (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.6/node_modules/brighterscript/dist/Program.js:673:36)
    at /Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.6/node_modules/brighterscript/dist/LanguageServer.js:815:134
    at Array.map (<anonymous>)
    at LanguageServer.onSignatureHelp (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.6/node_modules/brighterscript/dist/LanguageServer.js:815:91)
```

**Comment by TwitchBronBron** [comment]
I couldn't figure out how to reproduce this with code, but I do see the problem so I can submit a fix. Do you know what you were typing that triggered this?

**Comment by chrisdp** [comment]
@TwitchBronBron sadly I didn't catch what caused this one. Sorry. I will keep an eye out though and if I'm able to get it again and figure out the cause I'll let you know. I was working in a class. I can say that much.
