### ISSUE TITLE
Parser crash with unterminated #if

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/brighterscript#437]
Having `#if` without closing `#end if` causes VSCode to emit errors on each keypress.
```
 Message: Request textDocument/codeAction failed with message: TypeError: Cannot read property 'end' of undefined
    at Util.rangesIntersect (/Users/philippe.elsass/.vscode/extensions/rokucommunity.brightscript-2.22.3/node_modules/brighterscript/dist/util.js:438:15)
    at /Users/philippe.elsass/.vscode/extensions/rokucommunity.brightscript-2.22.3/node_modules/brighterscript/dist/Program.js:669:42
```

**Comment by elsassph** [comment]
Duplicate of #429
