### ISSUE TITLE
Cannot read property "shift" of undefined

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#71]
https://github.com/georgejecook/MList

> typeError: Cannot read property 'shift' of undefined
>     at XmlFile.<anonymous> (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/src/files/XmlFile.ts:219:58)
>     at step (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:43:23)
>     at Object.next (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:24:53)
>     at fulfilled (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:15:58)
>     at <anonymous>
> TypeError: Cannot read property 'shift' of undefined
>     at XmlFile.<anonymous> (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/src/files/XmlFile.ts:219:58)
>     at step (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:43:23)
>     at Object.next (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:24:53)
>     at fulfilled (/home/<username>/hope/open-source/MList/node_modules/brightscript-language/dist/files/XmlFile.js:15:58)

**Comment by TwitchBronBron** [comment]
This is probably related to the `autoIncludeComponentScript` property, since that thing doesn't set a valid range.
