### ISSUE TITLE
BscPlugin.onFileValidate throws error

### ISSUE THREAD

**Issue by tomek-r** [rokucommunity/brighterscript#751]
Hi,
Unfortunately, I can't provide the steps to reproduce the issue. I have no idea why it throws an error. The previous version I used 0.56.0 does not throw it.
 
Affected brighterscript version 0.60.6

```js
Error when calling plugin BscPlugin.onFileValidate: TypeError: Cannot read properties of undefined (reading 'text')
    at validateLoopTypeMatch (/Users/user/.../node_modules/brighterscript/dist/bscPlugin/validation/BrsFileValidator.js:236:131)
    at /Users/user/.../node_modules/brighterscript/dist/bscPlugin/validation/BrsFileValidator.js:251:17
```

**Comment by tomek-r** [comment]
You are super fast. Impressive! Thanks
