### ISSUE TITLE
"createPackage": true causes crash

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#764]
results in this output 
```Error: rootDir does not exist at "/var/lib/jenkins/~/hope/nba/nba-roku/build"
    at RokuDeploy.copyToStaging (/var/lib/jenkins/~/hope/nba/nba-roku/node_modules/roku-deploy/dist/RokuDeploy.js:311:19)
    at async RokuDeploy.prepublishToStaging (/var/lib/jenkins/~/hope/nba/nba-roku/node_modules/roku-deploy/dist/RokuDeploy.js:35:9)
    at async RokuDeploy.createPackage (/var/lib/jenkins/~/hope/nba/nba-roku/node_modules/roku-deploy/dist/RokuDeploy.js:115:9)
    at async RokuDeploy.deploy (/var/lib/jenkins/~/hope/nba/nba-roku/node_modules/roku-deploy/dist/RokuDeploy.js:612:9)
    at async RokuDeploy.deployAndSignPackage (/var/lib/jenkins/~/hope/nba/nba-roku/node_modules/roku-deploy/dist/RokuDeploy.js:690:9)
    at async deploy (/var/lib/jenkins/~/hope/nba/nba-roku/build-scripts/ci/run-ci.js:344:9)
    at async buildAndPackage (/var/lib/jenkins/~/hope/nba/nba-roku/build-scripts/ci/run-ci.js:275:5)
    at async runCI (/var/lib/jenkins/~/hope/nba/nba-roku/build-scripts/ci/run-ci.js:135:13)
```

**Comment by TwitchBronBron** [comment]
Closing this as inactive. If this is still an issue, please provide reproducible steps and we'll be happy to investigate.
